//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace university_registration_project_cris
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PROFESSOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PROFESSOR()
        {
            this.T_SCHEDULE = new HashSet<T_SCHEDULE>();
        }
    
        public int professor_id { get; set; }
        public string professor_personal_id { get; set; }
        public string professor_full_name { get; set; }
        public string professor_hire_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SCHEDULE> T_SCHEDULE { get; set; }
    }
}
