//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace university_registration_project_cris
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SCORE
    {
        public int score_id { get; set; }
        public int student_id { get; set; }
        public int schedule_id { get; set; }
        public string final_score { get; set; }
        public string score_status { get; set; }
    
        public virtual T_SCHEDULE T_SCHEDULE { get; set; }
        public virtual T_STUDENT T_STUDENT { get; set; }
    }
}
