//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace university_registration_project_cris
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SCHEDULE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_SCHEDULE()
        {
            this.T_REGISTRATION = new HashSet<T_REGISTRATION>();
            this.T_SCORE = new HashSet<T_SCORE>();
        }
    
        public int schedule_id { get; set; }
        public int course_id { get; set; }
        public int campus_id { get; set; }
        public int professor_id { get; set; }
        public int schedule_capacity { get; set; }
        public string schedule_period { get; set; }
        public string schedule_dates { get; set; }
    
        public virtual T_CAMPUS T_CAMPUS { get; set; }
        public virtual T_COURSE T_COURSE { get; set; }
        public virtual T_PROFESSOR T_PROFESSOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_REGISTRATION> T_REGISTRATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SCORE> T_SCORE { get; set; }
    }
}
