//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace university_registration_project_cris
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class T_STUDENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_STUDENT()
        {
            this.T_REGISTRATION = new HashSet<T_REGISTRATION>();
            this.T_SCORE = new HashSet<T_SCORE>();
        }

        public int student_id { get; set; }

        [Display(Name = "Identificación Personal")]
        public string student_personal_id { get; set; }

        [Display(Name = "Nombre")]
        public string student_name { get; set; }

        [Display(Name = "Primer Apellido")]
        public string student_last_name1 { get; set; }

        [Display(Name = "Segundo Apellido")]
        public string student_last_name2 { get; set; }

        [Display(Name = "Fecha de Nacimiento")]
        public string student_date_of_birth { get; set; }

        [Display(Name = "Fecha de Admisión")]
        public string student_admission_date { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_REGISTRATION> T_REGISTRATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SCORE> T_SCORE { get; set; }
    }
}
